[workspace]
resolver = "2"
members = ["jeez", "hypr", "state"]

[workspace.dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
log = "0.4.22"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.125"
strum_macros = "0.26.4"
tokio = { version = "1.39.2", features = ["full", "net"] }
