[package]
name = "hypr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
strum_macros.workspace = true
tokio.workspace = true
