[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
hypr = { path = "../hypr" }
serde.workspace = true
serde_json.workspace = true
log.workspace = true
anyhow.workspace = true
